/** 生成只依赖发布 tarball 的可复制示例，不发布包或复制 node_modules。 */

import { execFileSync } from 'node:child_process'
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { basename, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repositoryRoot = resolve(import.meta.dirname, '..')
const exampleRoot = join(repositoryRoot, 'examples/task-journal')
const marker = '.nya-example-bundle'
const packageNames = ['@nya/core', '@nya/loader', '@nya/logger-console', '@nya/timer']

export function createExampleBundle(destination, packages) {
  const directory = resolve(destination)
  // 只覆盖本脚本生成的目录；调用方传入的是固定 artifacts 路径或新建临时目录。
  if (existsSync(directory)) {
    if (!existsSync(join(directory, marker))) {
      throw new Error(`refusing to replace an unmarked directory: ${directory}`)
    }
    rmSync(directory, { recursive: true, force: true })
  }
  mkdirSync(directory, { recursive: true })
  writeFileSync(join(directory, marker), 'Generated by npm run example:pack.\n')
  for (const entry of [
    'src', 'dist', 'scripts', 'tests', 'config.json', 'README.md', 'tsconfig.json', 'tsconfig.test.json',
  ]) {
    cpSync(join(exampleRoot, entry), join(directory, entry), { recursive: true })
  }

  const manifest = JSON.parse(readFileSync(join(exampleRoot, 'package.json'), 'utf8'))
  manifest.dependencies = {}
  mkdirSync(join(directory, 'vendor'))
  for (const name of packageNames) {
    const entry = packages.find(item => item.name === name)
    if (!entry) throw new Error(`missing example dependency: ${name}`)
    const filename = basename(entry.tarball)
    cpSync(entry.tarball, join(directory, 'vendor', filename))
    manifest.dependencies[name] = `file:./vendor/${filename}`
  }
  writeFileSync(join(directory, 'package.json'), `${JSON.stringify(manifest, null, 2)}\n`)
  return directory
}

function pack() {
  const npmCli = process.env.npm_execpath
  if (!npmCli) throw new Error('run this command through npm run example:pack')
  const destination = join(repositoryRoot, 'artifacts/task-journal')
  const staging = join(repositoryRoot, 'artifacts/task-journal-packages')
  mkdirSync(staging, { recursive: true })
  const env = { ...process.env }
  delete env.npm_config_dry_run
  delete env.NPM_CONFIG_DRY_RUN
  const packages = packageNames.map(name => {
    const [result] = JSON.parse(execFileSync(process.execPath, [
      npmCli, 'pack', '--workspace', name, '--pack-destination', staging, '--json',
    ], { cwd: repositoryRoot, env, encoding: 'utf8' }))
    return { name, tarball: join(staging, result.filename) }
  })
  createExampleBundle(destination, packages)
  console.log(`独立示例已生成：${destination}`)
  console.log('复制该目录后运行 npm install、npm run build、npm run demo。')
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) pack()
