/** 生成可搬移的本地发布候选目录；不安装依赖，也不发布 npm 包。 */

import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import {
  cpSync, existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync,
  realpathSync, rmSync, writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createExampleBundle } from './pack-example.mjs'

const repositoryRoot = resolve(import.meta.dirname, '..')
const artifactRoot = join(repositoryRoot, 'artifacts')
const temporaryRoot = resolve(tmpdir())
const marker = '.nya-release-bundle'
const stagingMarker = '.nya-release-staging'
const markerContent = 'Generated by scripts/pack-release.mjs.\n'
const packageNames = ['@nya/core', '@nya/loader', '@nya/logger-console', '@nya/timer']
const documents = new Map([
  ['CHANGELOG.md', 'CHANGELOG.md'],
  ['docs/compatibility.md', 'COMPATIBILITY.md'],
  ['docs/how-to/migrate-0.1.md', 'MIGRATION.md'],
  ['docs/tutorials/framework-basics.md', 'TUTORIAL.md'],
  ['examples/task-journal/README.md', 'task-journal/README.md'],
])

function isDescendant(root, target) {
  const path = relative(root, target)
  return path !== '' && path !== '..' && !path.startsWith(`..${sep}`) && !isAbsolute(path)
}

// 未创建的目标也按最近存在祖先的真实路径校验，阻止父目录中的 junction/symlink 越界。
function canonicalPath(path) {
  if (existsSync(path)) return realpathSync(path)
  const parent = dirname(path)
  if (parent === path) throw new Error(`cannot resolve destination: ${path}`)
  return join(canonicalPath(parent), basename(path))
}

function validateDestination(destination) {
  if (typeof destination !== 'string' || !isAbsolute(destination)) {
    throw new Error('release destination must be an absolute path')
  }
  const directory = resolve(destination)
  const allowed = [artifactRoot, temporaryRoot].some(root => (
    isDescendant(root, directory)
    && isDescendant(canonicalPath(root), canonicalPath(directory))
  ))
  if (!allowed) throw new Error(`release destination must be below artifacts or the system temp directory: ${directory}`)
  if (existsSync(directory)) {
    const stat = lstatSync(directory)
    if (!stat.isDirectory() || stat.isSymbolicLink()) {
      throw new Error(`release destination must be a regular directory: ${directory}`)
    }
  }
  return directory
}

function removeMarkedDirectory(destination, markerName) {
  const directory = validateDestination(destination)
  const markerPath = join(directory, markerName)
  if (!existsSync(markerPath)
    || !lstatSync(markerPath).isFile()
    || lstatSync(markerPath).isSymbolicLink()
    || readFileSync(markerPath, 'utf8') !== markerContent) {
    throw new Error(`refusing to replace an unmarked directory: ${directory}`)
  }
  rmSync(directory, { recursive: true, force: true })
}

function rewriteMarkdown(markdown, source, destination, repositoryUrl) {
  function rewriteTarget(raw) {
    const angled = raw.startsWith('<') && raw.endsWith('>')
    const target = angled ? raw.slice(1, -1) : raw
    if (/^(?:[a-z][a-z\d+.-]*:|\/\/|#)/i.test(target)) return raw
    const suffixIndex = target.search(/[?#]/)
    const path = suffixIndex < 0 ? target : target.slice(0, suffixIndex)
    const suffix = suffixIndex < 0 ? '' : target.slice(suffixIndex)
    if (!path) return raw
    const decoded = decodeURIComponent(path)
    const sourceTarget = resolve(
      decoded.startsWith('/') ? repositoryRoot : dirname(join(repositoryRoot, source)),
      decoded.startsWith('/') ? `.${decoded}` : decoded,
    )
    if (!isDescendant(repositoryRoot, sourceTarget) && sourceTarget !== repositoryRoot) {
      throw new Error(`documentation link leaves the repository: ${source}: ${target}`)
    }
    const sourceRelative = relative(repositoryRoot, sourceTarget).split(sep).join('/')
    const mapped = documents.get(sourceRelative)
    // task-journal 自身随包提供的源码、配置和测试仍然可离线打开。
    const exampleLocal = source === 'examples/task-journal/README.md'
      && sourceRelative.startsWith('examples/task-journal/')
      ? sourceRelative.replace(/^examples\/task-journal\//, 'task-journal/')
      : undefined
    const output = mapped ?? exampleLocal
    const rewritten = output
      ? relative(dirname(join('/', destination)), join('/', output)).split(sep).join('/')
      : `${repositoryUrl}/blob/main/${sourceRelative.split('/').map(encodeURIComponent).join('/')}`
    return angled ? `<${rewritten}${suffix}>` : `${rewritten}${suffix}`
  }

  // 保留教程代码块原文，只处理 Markdown 正文中的内联链接和引用定义。
  let fence
  return markdown.split(/(?<=\n)/).map(line => {
    const delimiter = /^ {0,3}(`{3,}|~{3,})/.exec(line)?.[1]
    if (fence) {
      if (delimiter?.[0] === fence[0] && delimiter.length >= fence.length) fence = undefined
      return line
    }
    if (delimiter) {
      fence = delimiter
      return line
    }
    return line
      .replace(/(!?\[[^\]\n]*\]\()(<[^>\n]+>|[^\s)]+)([^\n)]*\))/g,
        (_match, prefix, target, suffix) => `${prefix}${rewriteTarget(target)}${suffix}`)
      .replace(/^( {0,3}\[[^\]\n]+\]:\s*)(<[^>\n]+>|\S+)(.*)$/,
        (_match, prefix, target, suffix) => `${prefix}${rewriteTarget(target)}${suffix}`)
  }).join('')
}

function releaseReadme(manifest, packages, repositoryUrl) {
  const installs = packages.map(entry => `./${entry.path}`).join(' ')
  return `# Nya ${manifest.version} 本地发布候选

这是用于验证的 RC 产物，不表示这些版本已发布到 npm。需要 Node.js 22.12 或更高版本。整个目录可以移动到仓库之外；不要复制仓库的 node_modules。

- [变更记录](./CHANGELOG.md)
- [兼容性与支持范围](./COMPATIBILITY.md)
- [迁移指南](./MIGRATION.md)
- [从零学习组件、服务与生命周期](./TUTORIAL.md)
- [Task Journal 使用说明](./task-journal/README.md)

核心教程正文和本目录内的发行说明可以离线阅读。教程中的四个 tarball 已放在 vendor/，直接复制到新项目即可，无须先取得或打包源码。深入阅读的源码与其他文档链接指向 [GitHub 仓库](${repositoryUrl})；阅读时请核对候选版本对应的源码，链接所示 main 分支可能已变化。

## 从本地包开始

新建项目目录，把本目录的 vendor/ 完整复制到其中，然后执行：

\`\`\`bash
npm init -y
npm install ${installs}
\`\`\`

Nya 四包来自本地归档。npm install 仍需按 npm 配置获取传递依赖；示例构建与测试工具也需要安装，因此本产物不是完全离线安装包。TypeScript 项目的完整配置和可运行代码见 TUTORIAL.md。

## 运行 Task Journal

在本候选目录中执行：

\`\`\`bash
cd task-journal
npm install
npm run build
npm run demo
\`\`\`

demo 根据实际记录事件完成更新、启停和依赖恢复后退出。持续运行使用：

\`\`\`bash
npm start -- --config ./config.json
\`\`\`

Ctrl+C 请求关闭。请保留 task-journal 内 package.json 与 vendor/ 的相对位置；src/ 和 dist/ 都随目录提供。

## 验证归档

RELEASE.json 按包记录 name、version、sha256 和相对 path。SHA256SUMS 覆盖候选根目录 vendor/ 内的四个归档；task-journal/vendor/ 是相同归档的副本。

在候选根目录使用支持 sha256sum 的环境：

\`\`\`bash
sha256sum -c SHA256SUMS
\`\`\`

Windows PowerShell：

\`\`\`powershell
Get-Content SHA256SUMS | ForEach-Object {
  $expected, $archive = $_ -split '  ', 2
  $actual = (Get-FileHash -LiteralPath $archive -Algorithm SHA256).Hash.ToLowerInvariant()
  if ($actual -ne $expected) { throw "SHA-256 mismatch: $archive" }
}
\`\`\`
`
}

/** @param {string} destination @param {{ name: string, tarball: string }[]} packages */
export function createReleaseBundle(destination, packages) {
  const directory = validateDestination(destination)
  const manifest = JSON.parse(readFileSync(join(repositoryRoot, 'package.json'), 'utf8'))
  const repositoryUrl = manifest.repository.url.replace(/^git\+/, '').replace(/\.git$/, '')
  if (!Array.isArray(packages) || packages.length !== packageNames.length
    || new Set(packages.map(entry => entry.name)).size !== packageNames.length) {
    throw new Error('release requires exactly one tarball for each of the four Nya packages')
  }
  const archives = packageNames.map(name => {
    const entry = packages.find(item => item.name === name)
    if (!entry) throw new Error(`missing release dependency: ${name}`)
    const packageManifest = JSON.parse(readFileSync(
      join(repositoryRoot, 'packages', name.slice('@nya/'.length), 'package.json'), 'utf8',
    ))
    if (packageManifest.name !== name || packageManifest.version !== manifest.version) {
      throw new Error(`release package name/version differs from the workspace: ${name}`)
    }
    const tarball = resolve(entry.tarball)
    const filename = `${name.replace('@', '').replace('/', '-')}-${packageManifest.version}.tgz`
    if (basename(tarball) !== filename || !lstatSync(tarball).isFile()) {
      throw new Error(`release tarball must match ${name}@${packageManifest.version}: ${tarball}`)
    }
    if (isDescendant(canonicalPath(directory), canonicalPath(tarball))) {
      throw new Error(`release input would be removed with its destination: ${tarball}`)
    }
    return {
      name, version: packageManifest.version, tarball,
      sha256: createHash('sha256').update(readFileSync(tarball)).digest('hex'),
      path: `vendor/${filename}`,
    }
  })
  // 缺少文档或示例构建产物时，在删除上一次候选之前失败。
  const copiedDocuments = [...documents].map(([source, target]) => ({
    target,
    content: rewriteMarkdown(readFileSync(join(repositoryRoot, source), 'utf8'), source, target, repositoryUrl),
  }))
  for (const entry of ['src', 'dist', 'scripts', 'tests', 'config.json', 'tsconfig.json', 'tsconfig.test.json', 'package.json']) {
    if (!existsSync(join(repositoryRoot, 'examples/task-journal', entry))) {
      throw new Error(`example bundle input is missing: ${entry}; build the workspace first`)
    }
  }
  if (existsSync(directory)) removeMarkedDirectory(directory, marker)
  mkdirSync(join(directory, 'vendor'), { recursive: true })
  writeFileSync(join(directory, marker), markerContent)
  for (const archive of archives) cpSync(archive.tarball, join(directory, archive.path))
  createExampleBundle(join(directory, 'task-journal'), archives)
  for (const document of copiedDocuments) writeFileSync(join(directory, document.target), document.content)
  writeFileSync(join(directory, 'RELEASE.json'), `${JSON.stringify({
    schemaVersion: 1,
    name: 'nya-release-candidate',
    version: manifest.version,
    node: manifest.engines.node,
    published: false,
    packages: archives.map(({ tarball: _tarball, ...entry }) => entry),
    documents: {
      changelog: 'CHANGELOG.md', compatibility: 'COMPATIBILITY.md',
      migration: 'MIGRATION.md', tutorial: 'TUTORIAL.md',
    },
    example: 'task-journal',
  }, null, 2)}\n`)
  writeFileSync(join(directory, 'SHA256SUMS'), archives.map(entry => `${entry.sha256}  ${entry.path}\n`).join(''))
  writeFileSync(join(directory, 'README.md'), releaseReadme(manifest, archives, repositoryUrl))
  return directory
}

function pack() {
  const npmCli = process.env.npm_execpath
  if (!npmCli) throw new Error('run this command through npm run release:pack')
  const staging = mkdtempSync(join(temporaryRoot, 'nya-release-pack-'))
  writeFileSync(join(staging, stagingMarker), markerContent)
  try {
    const env = { ...process.env }
    delete env.npm_config_dry_run
    delete env.NPM_CONFIG_DRY_RUN
    const packages = packageNames.map(name => {
      const [result] = JSON.parse(execFileSync(process.execPath, [
        npmCli, 'pack', '--workspace', name, '--pack-destination', staging, '--json',
      ], { cwd: repositoryRoot, env, encoding: 'utf8' }))
      if (result.name !== name || basename(result.filename) !== result.filename) {
        throw new Error(`unexpected npm pack result for ${name}`)
      }
      return { name, tarball: join(staging, result.filename) }
    })
    const directory = createReleaseBundle(join(artifactRoot, 'release-candidate'), packages)
    console.log(`本地发布候选已生成：${directory}`)
    console.log('版本与校验值见 RELEASE.json；安装、教程和示例见 README.md。未执行发布。')
  } finally {
    removeMarkedDirectory(staging, stagingMarker)
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) pack()
